import BaseTextItem from "../../../drawing/items/BaseTextItem";
import TextBoxItem from "../../../drawing/items/TextBoxItem";
import { Color, ContentAlignment, LineAlignment } from "../../../drawing/structures";
import SideTextStyleItem from "./SideTextStyleItem";
import SideTriangleStyleItem from "./SideTriangleStyleItem";
import YTLaneLocTypes from "../structures/YTLaneLocTypes";
import ContainerBaseYardItem from "./ContainerBaseYardItem";
import CustomTextItem from "./CustomTextItem";
import ShortItem from "./ShortItem";
import SideRectangleStyleItem from "./SideRectangleStyleItem";
import SymbolStyleItem from "./SymbolStyleItem";
import TriangleSymbolItem from "./TriangleSymbolItem";

class ContainerBayItem extends ContainerBaseYardItem {
    wType = 0;
    classCodeBackColor : Color;
    cntrNoUnderLineColor : Color;
    innerBorderColor : Color;
    cargoType : BaseTextItem;
    classCode : BaseTextItem;
    equipmentName : BaseTextItem;
    iMDG : BaseTextItem;
    containerRemark : BaseTextItem;
    bLNo : BaseTextItem;
    stackingDays : BaseTextItem;
    inboundVVD : BaseTextItem;
    lowerCaption : BaseTextItem;
    operatorCode : BaseTextItem;
    operatorBackColor = Color.Transparent();
    outboundVVD : BaseTextItem;
    planSequence : BaseTextItem;
    plugCheck : BaseTextItem;
    pod : BaseTextItem;
    podBackColor : Color;
    pol : BaseTextItem;
    shipBayBackColor : Color;
    lowerCaptionBackColor : Color;
    shipBayNo : BaseTextItem;
    size : BaseTextItem;
    sizeType : BaseTextItem;
    temperature : BaseTextItem;
    visibleCntrUnderLine = false;
    visibleCircle = false;
    visibleContainerNo = false;
    visibleReeferPlugInOut = false;
    visibleHoldCheck = false;
    visibleInvertedTriangle = false;
    visibleObliqueLine = false;
    visibleOccupied = false;
    visibleTriangle = false;
    weight : BaseTextItem;
    weightGroup : BaseTextItem;
    containerNo : BaseTextItem;
    obliqueLineColor : Color;
    isOVS = false;
    isOVP = false;
    isOVH = false;
    isOSS = false;
    isOSP = false;
    isOSH = false;
    overSlotColor : Color;
    overSizeColor : Color;
    occupiedColor : Color;
    triangleColor : Color;
    circleColor : Color;
    pECnt : number;
    visibleUnsync : boolean;
    unsyncColor : Color;
    visibleCntrState : boolean;
    isBookedCntr : boolean;
    caption = new BaseTextItem();
    backColorLeft : Color;
    backColorRight : Color;
    handlingInstruction : BaseTextItem;
    remarshallingSequence : BaseTextItem;
    remarshallingInOrder? : ShortItem;
    remarshallingOutOrder? : ShortItem;
    iMDGSymbol? : SymbolStyleItem;
    cargoTypeBackColor : Color;
    jobCode? : TextBoxItem;
    thinTriangle? : TriangleSymbolItem;
    visibleDamageCheck : boolean;
    damageCheckBackColor : Color;
    damageCheckBorderColor : Color;
    customTextItem? : CustomTextItem[];
    jobSequence : BaseTextItem;
    totalQty : BaseTextItem;
    outerLeftSideTriangle? : SideTriangleStyleItem;
    outerTopSideTriangle? : SideTriangleStyleItem;
    outerRightSideTriangle? : SideTriangleStyleItem;
    innerTopSideTriangle? : SideTriangleStyleItem;
    innerLeftSideText? : SideTextStyleItem;
    innerTopSideText? : SideTextStyleItem;
    innerRightSideText? : SideTextStyleItem;
    outerSideRectangle? : SideRectangleStyleItem;
    cellBookMark = false;
    cellBookMarkBackColor = Color.Transparent();
    cellBookMarkLineColor = Color.Transparent();
    reeferPlugInOutLineColor = Color.Transparent();
    reeferPlugInOutBackColor = Color.Transparent();
    reeferPlugInOutLineThick = 1;
    ytLaneLocTypes = YTLaneLocTypes.None;
    bookingNo : BaseTextItem;
    visibleDiamondSymbol = false;
    diamondSymbolStyle? : SymbolStyleItem;
    borderWidth = 0;
    borderAlignment = LineAlignment.Center;
    handlingInstructionBorderWidth = 0;
    handlingInstructionBorderColor = Color.Transparent();
    handlingInstructionBackColor = Color.Transparent();
    gateOutReady = "N";

    constructor() {
        super();
        this.backColor = Color.White();
        this.borderColor = Color.Black();
        this.obliqueLineColor = Color.Black();
        this.innerBorderColor = Color.Transparent();
        this.shipBayBackColor = Color.Transparent();
        this.classCodeBackColor = Color.Transparent();
        this.podBackColor = Color.Transparent();
        this.lowerCaptionBackColor = Color.Transparent();
        this.triangleColor = Color.Red();
        this.circleColor = Color.Yellow();
        this.cntrNoUnderLineColor = Color.Black();
        this.occupiedColor = Color.LightGray();
        this.overSlotColor = Color.Black();
        this.overSizeColor = Color.Black();
        this.cargoType = new BaseTextItem();
        this.classCode = new BaseTextItem();
        this.containerNo = new BaseTextItem();
        this.equipmentName = new BaseTextItem();
        this.weightGroup = new BaseTextItem();
        this.weight = new BaseTextItem();
        this.temperature = new BaseTextItem();
        this.sizeType = new BaseTextItem();
        this.size = new BaseTextItem();
        this.shipBayNo = new BaseTextItem();
        this.pol = new BaseTextItem();
        this.pod = new BaseTextItem();
        this.stackingDays = new BaseTextItem();
        this.plugCheck = new BaseTextItem();
        this.planSequence = new BaseTextItem();
        this.outboundVVD = new BaseTextItem();
        this.operatorCode = new BaseTextItem();
        this.lowerCaption = new BaseTextItem();
        this.inboundVVD = new BaseTextItem();
        this.iMDG = new BaseTextItem();
        this.handlingInstruction = new BaseTextItem();
        this.handlingInstruction.fontName = "Tahoma"
        this.handlingInstruction.textAlign = ContentAlignment.MiddleRight;
        this.remarshallingSequence = new BaseTextItem();
        this.remarshallingSequence.fontSize = 9;
        this.containerRemark = new BaseTextItem();
        this.xBay = 0;
        this.pECnt = 0;
        this.unsyncColor = Color.LightGray();
        this.visibleUnsync = false;
        this.visibleCntrState = false;
        this.isBookedCntr = false;
        this.backColorLeft = Color.Transparent();
        this.backColorRight = Color.Transparent();
        this.cargoTypeBackColor = Color.Transparent();
        this.visibleDamageCheck = false;
        this.damageCheckBackColor = Color.Transparent();
        this.damageCheckBorderColor = Color.Transparent();
        this.jobSequence = new BaseTextItem();
        this.totalQty = new BaseTextItem();
        this.bLNo = new BaseTextItem();
        this.bookingNo = new BaseTextItem(); // added by JH.Tak (2019.03.08) 0061894: Add 'Booking No' in Bay View and Control Yard Job
    }
}

export default ContainerBayItem;